## 试题一

## 存在问题

全局变量使用不当

### 具体分析

`tx.origin`与`msg.sender`的使用问题：

`tx.origin`是整个调用链上最开始的用户地址。

`msg.sender`是当前函数的直接调用者的地址（可以是用户调用，也可能是合约间接调用）。

### 解决办法

根据具体业务情况慎重使用这个两个全局变量。

> 大多数情况，尤其是涉及**身份验证**、**权限控制**或**分发资金**的操作都应该优先使用`msg.sender`。



## 卷一



## 卷二

### 存在问题

- 没有检查用户输入

- 敏感操作没有权限校验（可选）

- 没有考虑整型数据溢出问题（可选）

### 具体分析

最严重的问题是没有对用户输入进行检查。

![image.png](https://img13.360buyimg.com/ddimg/jfs/t1/238373/37/5950/6974/6577b971Fb807f6cb/de3141a256f87491.jpg)

如果用户输入是负数则会导致冻结时间减少甚至直接消失。

这里的攻击手段就是利用了整型数据的溢出。

![image.png](https://img10.360buyimg.com/ddimg/jfs/t1/221933/27/38861/3008/6577b8b7Fc9186d05/cb7044fcb3297f1d.jpg)

![image.png](https://img12.360buyimg.com/ddimg/jfs/t1/232547/10/7250/5459/6577ba6fFf5b90ba3/77e16babbc4778e9.jpg)

lockTime是一个uint类型的数据。而uint数据是将第一位符号位也看作是数据位。将uint取最大值+1，导致数据溢出直接变成0，再减去冻结时间，结果就是当前冻结时间的相反数。用这个数当作参数调用`increaseLockTime`，导致冻结时间直接清零。

> 对整型数运算有兴趣的自行补充计算机原理相关知识。

### 处理方法

- Solidity `0.8.0` 之前的版本，在合约中引用 Safemath 库，在整型溢出时报错。
- Solidity `0.8.0` 之后的版本内置了 `Safemath`，因此几乎不存在这类问题。开发者有时会为了节省gas使用 `unchecked` 关键字在代码块中临时关闭整型溢出检测，这时要确保不存在整型溢出漏洞。



## 卷三

### 存在问题

由于本身存在资金锁死机制，但不能阻止资金的强制汇入，从而资金锁死状态。

### 具体分析

`slefdestruct`是以太坊的底层（低级别）操作，没有直接手段可以阻止。攻击者利用这个特性向具有**资金锁死机制**的合约中进行注入，导致该合约中所有的资金全部锁死。

> 不过真的要吐槽一下：虽然确实是个漏洞吧，但能利用这种两败俱伤的攻击手段的人也真的疯狂！用我的钱锁死你的钱，壕无人性啊😭。

```solidity
pragma solidity ^0.8.3;
contract EtherGame {
    uint public targetAmount = 7 ether;
    address public winner;
	
	// 存钱
    function deposit() public payable {
        require(msg.value == 1 ether, "You can only send 1 Ether");
        uint balance = address(this).balance;
        // 死锁机制：余额超过目标额度资源无法正常汇入
        // 强制注入导致合约余额超过目标额度，此时并没有赢家产生，无法将合约中的资金取走，合约中的资金进入死锁（不能存取）
        require(balance <= targetAmount, "Game is over");
        if (balance == targetAmount) {
            winner = msg.sender;
        }
    }
    
    // 赢家取走全部资金
    function claimReward() public {
        require(msg.sender == winner, "Not winner");
        (bool sent, ) = msg.sender.call{value: address(this).balance}("");
        require(sent, "Failed to send Ether");
    }
}
```

### 处理办法

**增加安全校验机制**

既然合约的真实余额是不能防止强制汇入的，那我们就新增一个**自定义余额**，通过自定义余额对合约状态进行管理。

```solidity
pragma solidity ^0.8.3;
contract EtherGame {
    uint public targetAmount = 7 ether;
    // 自定义余额
    uint private balance = 0; 
    address public winner;

    function deposit() public payable {
        require(msg.value == 1 ether, "You can only send 1 Ether");
        // 操作自定义余额
        balance += msg.value;
        require(balance <= targetAmount, "Game is over");
        if (balance == targetAmount) {
            winner = msg.sender;
        }
    }
    
    function claimReward() public {
        require(msg.sender == winner, "Not winner");
        (bool sent, ) = msg.sender.call{value: address(this).balance}("");
        require(sent, "Failed to send Ether");
    }
}
```



## 重入攻击

```solidity
contract Bank {
    mapping (address => uint256) public balanceOf;    // 余额mapping

    // 存入ether，并更新余额
    function deposit() external payable {
        balanceOf[msg.sender] += msg.value;
    }

    // 提取msg.sender的全部ether
    function withdraw() external {
        uint256 balance = balanceOf[msg.sender]; // 获取余额
        require(balance > 0, "Insufficient balance");
        // 存在重入攻击风险
        (bool success, ) = msg.sender.call{value: balance}("");
        require(success, "Failed to send Ether");
        // 更新余额
        balanceOf[msg.sender] = 0;
    }

    // 获取银行合约的余额
    function getBalance() external view returns (uint256) {
        return address(this).balance;
    }
}

contrack Attack {
	// 回调函数，用于重入攻击Bank合约，反复的调用目标的withdraw函数
    receive() external payable {
        if (bank.getBalance() >= 1 ether) {
            bank.withdraw();
        }
    }

	// 攻击函数，调用时 msg.value 设为 1 ether
    function attack() external payable {
        require(msg.value == 1 ether, "Require 1 Ether to attack");
        bank.deposit{value: 1 ether}();
        bank.withdraw();
    }
}
```



### 存在问题

- 业务设计漏洞
- `fallback`回退函数
- 取款操作没有使用重入锁

### 具体分析

重入攻击根本的讲，其实是利用了业务漏洞。

将银行的营业员全部想象成机器人（函数就是用户触发后进行工作）。

一般的用户取款流程是：

1. 用户调用取款函数
2. 转账到用户地址
3. 更新余额

![一般取款流程.png](https://img11.360buyimg.com/ddimg/jfs/t1/234956/12/8384/20787/657af6c2Fdd7a8e17/c9dd3ff6f69fbad1.jpg)

但如果收款的地址是一个合约的话，就会存在一个很**严重的问题**。这得提到合约的一个机制——合约的回调函数。它的工作原理是：当合约收到一份转账的时候，根据`msg.data`的状态及合约是否存在`receive()`函数决定调用`receive()`函数还是`fallback()`函数。

> 注意⚠️：在Solidity 0.6.x版本之前，语法上只有 `fallback()` 函数，用来接收用户发送的ETH时调用以及在被调用函数签名没有匹配到时，来调用。 0.6版本之后，Solidity才将 `fallback()` 函数拆分成 `receive()` 和 `fallback()` 两个函数。

<img src="https://img11.360buyimg.com/ddimg/jfs/t1/123723/36/38237/20551/657af8bdF40f99141/8a231744be4c5a8c.jpg" alt="falback.png" style="zoom: 50%;" />

**注意！重入攻击来了**：假设当机器人转账过来的时候调用的是`fallback()`回退函数，这个时候我们在`fallback`中再次调用银行的取款函数，并取出相同的数量。此时，由于机器人还没有执行到更新余额的函数，认为该用户账户中还有足够的余额，将会再次对用户进行转账。不断循环取款操作，直到掏空银行的全部余额。😵

### 处理方法

回忆一下该攻击的攻击点：利用合约收到转账后的`fallback()`再次取款，通过银行中用户余额更新不及时转移货币。

目前有两种解决方式：

- 使用**检查-影响-交互模式**：修改业务流程，弥补用户余额更新不及时的漏洞：

  1. 用户取款
  2. 更新用户余额
  3. 转账

- 使用**重入锁**：使用修饰符可以在函数执行先后执行的特性，在函数执行前，修改函数执行状态，在函数执行完毕后还原，并且函数执行过程中对函数执行状态进行校验。

  ```solidity
  contract Bank{
  	uint256 private _status; // 函数执行状态
  
      // 重入锁
      modifier nonReentrant() {
          // 在第一次调用 nonReentrant 时，_status 将是 0
          require(_status == 0, "ReentrancyGuard: reentrant call");
          // 在此之后对 nonReentrant 的任何调用都将失败
          _status = 1;
          _;
          // 调用结束，将 _status 恢复为0
          _status = 0;
  	}
  }
  ```

- PullPayment(拉取支付)模式：

  OpenZeppelin也提倡遵循PullPayment(拉取支付)模式以避免潜在的重入攻击。其原理是通过引入第三方(escrow)，将原先的“主动转账”分解为“**转账者发起转账**”加上“**接受者主动拉取**”。当想要发起一笔转账时，会通过`_asyncTransfer(address dest, uint256 amount)`将待转账金额存储到第三方合约中，从而避免因重入导致的自身资产损失。而当接受者想要接受转账时，需要主动调用`withdrawPayments(address payable payee)`进行资产的主动获取。

  > 银行转账到第三方时不会引起用户合约的`receive()`或`fallback()`函数，从而避免了重入攻击。
